// Frozen at G3 on 2026-10-05 from pipeline/output/. Generated by pipeline/freeze-core.mjs; do not edit by hand.
export default {
  "id": "brief-2026-06-19",
  "label": "frozen",
  "periodEnd": "2026-06-19",
  "periodStart": "2026-06-13",
  "provenance": {
    "frozenOn": "2026-10-05",
    "producedBy": [
      "brief-editor"
    ],
    "producedOn": "2026-10-04",
    "publishedOn": null,
    "publisher": null,
    "retrievedOn": null,
    "sourceUrl": null
  },
  "signalIds": [
    "sig-2026-02-10-zebra-alpha",
    "sig-2026-02-10-zebra-beta",
    "sig-2026-03-04-zebra-gamma",
    "sig-2026-05-20-zebra-delta",
    "sig-2026-06-15-zebra-epsilon"
  ]
};
