// Frozen at G3 on 2026-10-05 from pipeline/output/. Generated by pipeline/freeze-core.mjs; do not edit by hand.
export default {
  "frozenOn": "2026-10-05",
  "modules": [
    "data/brief.js",
    "data/conversation/trend-fixture-alpha.js",
    "data/conversation/trend-fixture-beta.js",
    "data/freeze.js",
    "data/governance.js",
    "data/log.js",
    "data/readiness.js",
    "data/reveal/trend-fixture-alpha.js",
    "data/reveal/trend-fixture-beta.js",
    "data/signals.js",
    "data/trends.js"
  ],
  "pipelineRunOn": "2026-10-04"
};
