// Frozen at G3 on 2026-10-05 from pipeline/output/. Generated by pipeline/freeze-core.mjs; do not edit by hand.
export default {
  "argument": [
    {
      "id": "zebra-argument-one",
      "label": "ai-generated",
      "sources": [
        {
          "publishedOn": "2026-02-01",
          "publisher": "Example Fixture Publisher",
          "retrievedOn": "2026-10-01",
          "title": "Fixture regulation page",
          "url": "https://example.org/fixture/governance-one"
        }
      ],
      "text": "zebra-argument-one-text: a synthetic paragraph stating a condition, for tests."
    },
    {
      "id": "zebra-argument-two",
      "label": "ai-generated",
      "sources": [
        {
          "publishedOn": "2026-03-01",
          "publisher": "Example Fixture Publisher",
          "retrievedOn": "2026-10-01",
          "url": "https://example.org/fixture/governance-two"
        },
        {
          "publishedOn": "2026-04-01",
          "publisher": "Example Fixture Publisher",
          "retrievedOn": "2026-10-01",
          "url": "https://example.org/fixture/governance-three"
        }
      ],
      "text": "zebra-argument-two-text: a second synthetic paragraph, for tests."
    }
  ],
  "id": "governance",
  "implemented": [
    {
      "id": "open-web-sources-frozen",
      "text": "zebra-governance-open-web: synthetic statement for tests.",
      "verifiedBy": [
        "M1-U16"
      ]
    },
    {
      "id": "no-viewer-data-stored-or-sent",
      "text": "zebra-governance-no-viewer-data: synthetic statement for tests.",
      "verifiedBy": [
        "M10-U2",
        "M6-U9"
      ]
    },
    {
      "id": "no-live-ai",
      "text": "zebra-governance-no-live-ai: synthetic statement for tests.",
      "verifiedBy": [
        "M10-U1",
        "M10-U4"
      ]
    },
    {
      "id": "no-accounts-cookies-analytics",
      "text": "zebra-governance-no-accounts: synthetic statement for tests.",
      "verifiedBy": [
        "M10-U2"
      ]
    }
  ],
  "label": "real",
  "notImplemented": [
    {
      "id": "own-data-ingestion",
      "text": "zebra-governance-own-data: synthetic statement for tests.",
      "verifiedBy": [
        "M10-U1",
        "M10-U4"
      ]
    },
    {
      "id": "cross-session-persistence",
      "text": "zebra-governance-persistence: synthetic statement for tests.",
      "verifiedBy": [
        "M10-U2",
        "M6-U9"
      ]
    },
    {
      "id": "role-aware-model",
      "text": "zebra-governance-roles: synthetic statement for tests.",
      "verifiedBy": [
        "M8-U8"
      ]
    }
  ],
  "provenance": {
    "frozenOn": "2026-10-05",
    "producedBy": [
      "architect"
    ],
    "producedOn": "2026-10-04",
    "publishedOn": null,
    "publisher": null,
    "retrievedOn": null,
    "sourceUrl": null
  }
};
