// Frozen at G3 on 2026-10-05 from pipeline/output/. Generated by pipeline/freeze-core.mjs; do not edit by hand.
export default [
  {
    "calibrationNote": {
      "label": "ai-generated",
      "text": "zebra-replay-2026-01-01-zebra-log-one-calibration: a synthetic qualitative note for tests."
    },
    "id": "replay-2026-01-01-zebra-log-one",
    "label": "replay",
    "originalSignals": [
      {
        "label": "real",
        "source": {
          "publishedOn": "2026-01-01",
          "publisher": "Example Fixture Publisher",
          "retrievedOn": "2026-10-01",
          "url": "https://example.org/fixture/replay-one-a"
        },
        "summary": {
          "label": "ai-generated",
          "text": "zebra-replay-one-a-summary: a synthetic paraphrase for tests."
        },
        "title": "Zebra replay one-a fixture headline"
      },
      {
        "label": "real",
        "source": {
          "publishedOn": "2026-01-20",
          "publisher": "Example Fixture Publisher",
          "retrievedOn": "2026-10-01",
          "url": "https://example.org/fixture/replay-one-b"
        },
        "summary": {
          "label": "ai-generated",
          "text": "zebra-replay-one-b-summary: a synthetic paraphrase for tests."
        },
        "title": "Zebra replay one-b fixture headline"
      }
    ],
    "outcome": {
      "attachedOn": "2026-10-04",
      "label": "real",
      "source": {
        "publishedOn": "2026-06-10",
        "publisher": "Example Fixture Publisher",
        "retrievedOn": "2026-10-01",
        "url": "https://example.org/fixture/replay-2026-01-01-zebra-log-one-outcome"
      },
      "summary": {
        "label": "ai-generated",
        "text": "zebra-replay-2026-01-01-zebra-log-one-outcome: a synthetic outcome paraphrase for tests."
      }
    },
    "pastJudgement": {
      "asOfDate": "2026-01-25",
      "authoredBy": [
        "rival-reader",
        "interrogator"
      ],
      "authoredOn": "2026-10-03",
      "label": "replay",
      "lens": "threat",
      "rationale": "zebra-replay-2026-01-01-zebra-log-one-rationale: a synthetic past judgement for tests."
    },
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "rival-reader",
        "interrogator",
        "verifier"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": null,
      "publisher": null,
      "retrievedOn": null,
      "sourceUrl": null
    }
  },
  {
    "calibrationNote": {
      "label": "ai-generated",
      "text": "zebra-replay-2026-02-14-zebra-log-two-calibration: a synthetic qualitative note for tests."
    },
    "id": "replay-2026-02-14-zebra-log-two",
    "label": "replay",
    "originalSignals": [
      {
        "label": "real",
        "source": {
          "publishedOn": "2026-02-14",
          "publisher": "Example Fixture Publisher",
          "retrievedOn": "2026-10-01",
          "url": "https://example.org/fixture/replay-two"
        },
        "summary": {
          "label": "ai-generated",
          "text": "zebra-replay-two-summary: a synthetic paraphrase for tests."
        },
        "title": "Zebra replay two fixture headline"
      }
    ],
    "outcome": {
      "attachedOn": "2026-10-04",
      "label": "real",
      "source": {
        "publishedOn": "2026-07-01",
        "publisher": "Example Fixture Publisher",
        "retrievedOn": "2026-10-01",
        "url": "https://example.org/fixture/replay-2026-02-14-zebra-log-two-outcome"
      },
      "summary": {
        "label": "ai-generated",
        "text": "zebra-replay-2026-02-14-zebra-log-two-outcome: a synthetic outcome paraphrase for tests."
      }
    },
    "pastJudgement": {
      "asOfDate": "2026-02-20",
      "authoredBy": [
        "rival-reader",
        "interrogator"
      ],
      "authoredOn": "2026-10-03",
      "label": "replay",
      "lens": "opportunity",
      "rationale": "zebra-replay-2026-02-14-zebra-log-two-rationale: a synthetic past judgement for tests."
    },
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "rival-reader",
        "interrogator",
        "verifier"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": null,
      "publisher": null,
      "retrievedOn": null,
      "sourceUrl": null
    }
  },
  {
    "calibrationNote": {
      "label": "ai-generated",
      "text": "zebra-replay-2026-03-31-zebra-log-three-calibration: a synthetic qualitative note for tests."
    },
    "id": "replay-2026-03-31-zebra-log-three",
    "label": "replay",
    "originalSignals": [
      {
        "label": "real",
        "source": {
          "publishedOn": "2026-03-31",
          "publisher": "Example Fixture Publisher",
          "retrievedOn": "2026-10-01",
          "url": "https://example.org/fixture/replay-three"
        },
        "summary": {
          "label": "ai-generated",
          "text": "zebra-replay-three-summary: a synthetic paraphrase for tests."
        },
        "title": "Zebra replay three fixture headline"
      }
    ],
    "outcome": {
      "attachedOn": "2026-10-04",
      "label": "real",
      "source": {
        "publishedOn": "2026-09-01",
        "publisher": "Example Fixture Publisher",
        "retrievedOn": "2026-10-01",
        "url": "https://example.org/fixture/replay-2026-03-31-zebra-log-three-outcome"
      },
      "summary": {
        "label": "ai-generated",
        "text": "zebra-replay-2026-03-31-zebra-log-three-outcome: a synthetic outcome paraphrase for tests."
      }
    },
    "pastJudgement": {
      "asOfDate": "2026-03-31",
      "authoredBy": [
        "rival-reader",
        "interrogator"
      ],
      "authoredOn": "2026-10-03",
      "label": "replay",
      "lens": "noise",
      "rationale": "zebra-replay-2026-03-31-zebra-log-three-rationale: a synthetic past judgement for tests."
    },
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "rival-reader",
        "interrogator",
        "verifier"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": null,
      "publisher": null,
      "retrievedOn": null,
      "sourceUrl": null
    }
  }
];
