// Frozen at G3 on 2026-10-05 from pipeline/output/. Generated by pipeline/freeze-core.mjs; do not edit by hand.
export default {
  "categories": [
    {
      "answers": [
        {
          "answer": "zebra-strategic-alignment-answer: a synthetic dossier answer.",
          "question": "zebra-strategic-alignment-question: a synthetic dossier question?"
        }
      ],
      "finding": "zebra-strategic-alignment-finding: a synthetic finding in prose.",
      "key": "strategic-alignment",
      "name": "Strategic alignment"
    },
    {
      "answers": [
        {
          "answer": "zebra-resources-answer: a synthetic dossier answer.",
          "question": "zebra-resources-question: a synthetic dossier question?"
        }
      ],
      "finding": "zebra-resources-finding: a synthetic finding in prose.",
      "key": "resources",
      "name": "Resources"
    },
    {
      "answers": [
        {
          "answer": "zebra-knowledge-answer: a synthetic dossier answer.",
          "question": "zebra-knowledge-question: a synthetic dossier question?"
        }
      ],
      "finding": "zebra-knowledge-finding: a synthetic finding in prose.",
      "key": "knowledge",
      "name": "Knowledge"
    },
    {
      "answers": [
        {
          "answer": "zebra-culture-answer: a synthetic dossier answer.",
          "question": "zebra-culture-question: a synthetic dossier question?"
        }
      ],
      "finding": "zebra-culture-finding: a synthetic finding in prose.",
      "key": "culture",
      "name": "Culture"
    },
    {
      "answers": [
        {
          "answer": "zebra-data-answer: a synthetic dossier answer.",
          "question": "zebra-data-question: a synthetic dossier question?"
        }
      ],
      "finding": "zebra-data-finding: a synthetic finding in prose.",
      "key": "data",
      "name": "Data"
    }
  ],
  "framework": {
    "citation": {
      "publishedOn": "2021-01-15",
      "publisher": "Example Journal",
      "retrievedOn": "2026-10-01",
      "title": "Fixture framework paper",
      "url": "https://example.org/fixture/readiness-framework"
    },
    "label": "real",
    "name": "Fixture readiness framework"
  },
  "id": "readiness-fixture-team",
  "label": "fictional",
  "maturity": {
    "practices": [
      {
        "betweenLevels": null,
        "explanation": null,
        "key": "scanning",
        "levelName": "LEVEL_NAME_UNVERIFIED",
        "name": "Scanning",
        "nextLevel": null
      },
      {
        "betweenLevels": null,
        "explanation": null,
        "key": "trend-analysis",
        "levelName": "LEVEL_NAME_UNVERIFIED",
        "name": "Trend analysis",
        "nextLevel": null
      },
      {
        "betweenLevels": null,
        "explanation": null,
        "key": "scenario-work",
        "levelName": "LEVEL_NAME_UNVERIFIED",
        "name": "Scenario work",
        "nextLevel": null
      }
    ],
    "report": null,
    "status": "unverified"
  },
  "provenance": {
    "frozenOn": "2026-10-05",
    "producedBy": [
      "persona-researcher"
    ],
    "producedOn": "2026-10-04",
    "publishedOn": null,
    "publisher": null,
    "retrievedOn": null,
    "sourceUrl": null
  },
  "subject": "Fixture team (fictional test data)"
};
