// Frozen at G3 on 2026-10-05 from pipeline/output/. Generated by pipeline/freeze-core.mjs; do not edit by hand.
export default [
  {
    "id": "sig-2026-02-10-zebra-alpha",
    "label": "real",
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "scout"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": "2026-02-10",
      "publisher": "Example Gazette",
      "retrievedOn": "2026-10-01",
      "sourceUrl": "https://example.org/fixture/signal-zebra-alpha"
    },
    "relevanceNote": {
      "label": "ai-generated",
      "text": "zebra-alpha-relevance: a synthetic note on why the fixture team might look at this."
    },
    "sourceLanguage": "en",
    "summary": {
      "label": "ai-generated",
      "text": "zebra-alpha-summary: a synthetic paraphrase of a made-up source, used only by the unit tests."
    },
    "title": "Zebra alpha fixture headline about synthetic ingest tooling"
  },
  {
    "id": "sig-2026-02-10-zebra-beta",
    "label": "real",
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "scout"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": "2026-02-10",
      "publisher": "Example Weekly",
      "retrievedOn": "2026-10-01",
      "sourceUrl": "https://example.org/fixture/signal-zebra-beta"
    },
    "relevanceNote": {
      "label": "ai-generated",
      "text": "zebra-beta-relevance: a synthetic note on why the fixture team might look at this."
    },
    "sourceLanguage": "en",
    "summary": {
      "label": "ai-generated",
      "text": "zebra-beta-summary: a synthetic paraphrase of a made-up source, used only by the unit tests."
    },
    "title": "Zebra beta fixture headline about synthetic pricing pages"
  },
  {
    "id": "sig-2026-03-04-zebra-gamma",
    "label": "real",
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "scout"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": "2026-03-04",
      "publisher": "Beispiel Fachblatt",
      "retrievedOn": "2026-10-01",
      "sourceUrl": "https://example.org/fixture/signal-zebra-gamma"
    },
    "relevanceNote": {
      "label": "ai-generated",
      "text": "zebra-gamma-relevance: a synthetic note on why the fixture team might look at this."
    },
    "sourceLanguage": "de",
    "summary": {
      "label": "ai-generated",
      "text": "zebra-gamma-summary: a synthetic paraphrase of a made-up source, used only by the unit tests."
    },
    "title": "Zebra Gamma: synthetischer Normentwurf für Testzwecke"
  },
  {
    "id": "sig-2026-05-20-zebra-delta",
    "label": "real",
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "scout"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": "2026-05-20",
      "publisher": "Example Gazette",
      "retrievedOn": "2026-10-01",
      "sourceUrl": "https://example.org/fixture/signal-zebra-delta"
    },
    "quote": "zebra delta quote one two three four five six seven eight nine ten eleven twelve",
    "relevanceNote": {
      "label": "ai-generated",
      "text": "zebra-delta-relevance: a synthetic note on why the fixture team might look at this."
    },
    "sourceLanguage": "en",
    "summary": {
      "label": "ai-generated",
      "text": "zebra-delta-summary: a synthetic paraphrase of a made-up source, used only by the unit tests."
    },
    "title": "Zebra delta fixture headline about a synthetic rule draft"
  },
  {
    "id": "sig-2026-06-15-zebra-epsilon",
    "label": "real",
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "scout"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": "2026-06-15",
      "publisher": "Example Weekly",
      "retrievedOn": "2026-10-01",
      "sourceUrl": "https://example.org/fixture/signal-zebra-epsilon"
    },
    "relevanceNote": {
      "label": "ai-generated",
      "text": "zebra-epsilon-relevance: a synthetic note on why the fixture team might look at this."
    },
    "sourceLanguage": "en",
    "summary": {
      "label": "ai-generated",
      "text": "zebra-epsilon-summary: a synthetic paraphrase of a made-up source, used only by the unit tests."
    },
    "title": "Zebra epsilon fixture headline about synthetic hiring notes"
  },
  {
    "id": "sig-2025-11-02-zebra-zeta",
    "label": "real",
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "scout"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": "2025-11-02",
      "publisher": "Example Archive",
      "retrievedOn": "2026-10-01",
      "sourceUrl": "https://example.org/fixture/signal-zebra-zeta"
    },
    "relevanceNote": {
      "label": "ai-generated",
      "text": "zebra-zeta-relevance: a synthetic note on why the fixture team might look at this."
    },
    "sourceLanguage": "en",
    "summary": {
      "label": "ai-generated",
      "text": "zebra-zeta-summary: a synthetic paraphrase of a made-up source, used only by the unit tests."
    },
    "title": "Zebra zeta fixture headline from before the synthetic window",
    "windowNote": "Fixture note: published before the window of the synthetic scanning brief."
  }
];
