// Frozen at G3 on 2026-10-05 from pipeline/output/. Generated by pipeline/freeze-core.mjs; do not edit by hand.
export default [
  {
    "id": "trend-fixture-alpha",
    "intuitionPrompt": "zebra-alpha-intuition-prompt: before reading anything further, what is your gut reading of this movement?",
    "label": "ai-generated",
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "trend-analyst",
        "interrogator"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": null,
      "publisher": null,
      "retrievedOn": null,
      "sourceUrl": null
    },
    "readings": [
      {
        "lens": "opportunity",
        "readingId": "reading-fixture-alpha-opportunity"
      },
      {
        "lens": "threat",
        "readingId": "reading-fixture-alpha-threat"
      },
      {
        "lens": "noise",
        "readingId": "reading-fixture-alpha-noise"
      }
    ],
    "signalIds": [
      "sig-2026-02-10-zebra-alpha",
      "sig-2026-02-10-zebra-beta",
      "sig-2026-03-04-zebra-gamma"
    ],
    "summary": "zebra-alpha-trend-summary: synthetic signals describe a change in how example tools collect data over several months.",
    "title": "Zebra alpha fixture movement in synthetic tooling"
  },
  {
    "id": "trend-fixture-beta",
    "intuitionPrompt": "zebra-beta-intuition-prompt: before reading anything further, what is your gut reading of this movement?",
    "label": "ai-generated",
    "provenance": {
      "frozenOn": "2026-10-05",
      "producedBy": [
        "trend-analyst",
        "interrogator"
      ],
      "producedOn": "2026-10-04",
      "publishedOn": null,
      "publisher": null,
      "retrievedOn": null,
      "sourceUrl": null
    },
    "readings": [
      {
        "lens": "opportunity",
        "readingId": "reading-fixture-beta-opportunity"
      },
      {
        "lens": "threat",
        "readingId": "reading-fixture-beta-threat"
      },
      {
        "lens": "noise",
        "readingId": "reading-fixture-beta-noise"
      }
    ],
    "signalIds": [
      "sig-2026-03-04-zebra-gamma",
      "sig-2026-05-20-zebra-delta",
      "sig-2026-06-15-zebra-epsilon",
      "sig-2025-11-02-zebra-zeta"
    ],
    "summary": "zebra-beta-trend-summary: synthetic signals describe a change in how example tools collect data over several months.",
    "title": "Zebra beta fixture movement in synthetic tooling"
  }
];
