// M1 Data contracts: the freeze core (docs/03-architecture.md, section 4).
//
// A pure function from the parsed contents of pipeline/output/, the Verifier's record and the
// schemas to the complete set of data/ files as text, or to a list of errors. It performs no input
// or output of its own, so it runs unchanged under Node and in a browser. It uses only language
// built-ins, the Web Crypto API and the project's schema interpreter.
//
//   freeze({ inputs, verification, schemas, frozenOn, pipelineRunOn })
//     resolves to { ok: true, files } (a Map from repository path to file text)
//              or { ok: false, errors } (each message names the entity concerned); never throws.
//
// It refuses, producing no file at all, when any entity has no `pass` verdict, when the SHA-256 of
// an entity's canonical JSON differs from the hash the Verifier recorded, or when any entity, reveal
// bundle, conversation module or the manifest fails its schema. It never edits text: it wraps,
// regroups readings and interrogations by trend, and adds the manifest. Output is deterministic:
// arrays keep their input order, object keys are sorted, and the manifest lists its modules sorted
// by code point.

import { createValidator } from '../tests/lib/mini-schema.mjs';

const DATE = /^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/;

/** The pipeline/output/ files the core reads, the entity type each holds and its schema. */
const ARRAY_INPUTS = Object.freeze([
  { file: 'signals.json', schema: 'signal.schema.json' },
  { file: 'trends.json', schema: 'trend.schema.json' },
  { file: 'readings.json', schema: 'reading.schema.json' },
  { file: 'interrogations.json', schema: 'interrogation.schema.json' },
  { file: 'conversations.json', schema: 'conversation-questions.schema.json' },
  { file: 'log.json', schema: 'log-entry.schema.json' },
]);
const OBJECT_INPUTS = Object.freeze([
  { file: 'brief.json', schema: 'brief.schema.json' },
  { file: 'readiness.json', schema: 'readiness-profile.schema.json' },
  { file: 'governance.json', schema: 'governance.schema.json' },
]);

/** The input files, in the order the driver reads them. */
export const INPUT_FILES = Object.freeze([...ARRAY_INPUTS, ...OBJECT_INPUTS].map((x) => x.file));

export function headerLine(frozenOn) {
  return `// Frozen at G3 on ${frozenOn} from pipeline/output/. Generated by pipeline/freeze-core.mjs; do not edit by hand.`;
}

/** A copy of a JSON value with object keys sorted recursively; arrays keep their order. */
export function sortKeysDeep(value) {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (value !== null && typeof value === 'object') {
    const out = {};
    for (const key of Object.keys(value).sort()) out[key] = sortKeysDeep(value[key]);
    return out;
  }
  return value;
}

/** Canonical JSON: keys sorted recursively, no whitespace. */
export function canonicalJson(value) {
  return JSON.stringify(sortKeysDeep(value));
}

/** SHA-256 of the entity's canonical JSON (UTF-8), as lower-case hex. */
export async function entityHash(value) {
  const subtle = globalThis.crypto && globalThis.crypto.subtle;
  if (!subtle) throw new Error('the Web Crypto API (crypto.subtle) is not available');
  const digest = await subtle.digest('SHA-256', new TextEncoder().encode(canonicalJson(value)));
  return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, '0')).join('');
}

/** The text of one data module: the header line, then `export default <JSON>;` and one newline. */
export function moduleText(value, frozenOn) {
  return `${headerLine(frozenOn)}\nexport default ${JSON.stringify(sortKeysDeep(value), null, 2)};\n`;
}

const byCodePoint = (a, b) => {
  const x = Array.from(a, (c) => c.codePointAt(0));
  const y = Array.from(b, (c) => c.codePointAt(0));
  for (let i = 0; i < Math.min(x.length, y.length); i += 1) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
};

const isObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
const nameOf = (entity, fallback) => (isObject(entity) && typeof entity.id === 'string' ? entity.id : fallback);

export async function freeze({ inputs, verification, schemas, frozenOn, pipelineRunOn } = {}) {
  try {
    return await freezeOrRefuse({ inputs, verification, schemas, frozenOn, pipelineRunOn });
  } catch (error) {
    return { ok: false, errors: [`the freeze could not complete: ${error && error.message}`] };
  }
}

async function freezeOrRefuse({ inputs, verification, schemas, frozenOn, pipelineRunOn }) {
  const errors = [];

  // ---------------------------------------------------------------- arguments
  if (typeof frozenOn !== 'string' || !DATE.test(frozenOn)) errors.push(`frozenOn ${JSON.stringify(frozenOn)} is not an ISO date`);
  if (typeof pipelineRunOn !== 'string' || !DATE.test(pipelineRunOn)) errors.push(`pipelineRunOn ${JSON.stringify(pipelineRunOn)} is not an ISO date`);
  if (!isObject(inputs)) errors.push('inputs is not an object keyed by pipeline/output/ file name');
  if (!isObject(verification) || !Array.isArray(verification.entities)) errors.push('verification has no entities list');
  if (!isObject(schemas)) errors.push('schemas is not an object keyed by schema file name');
  if (errors.length) return { ok: false, errors };

  for (const { file } of ARRAY_INPUTS) if (!Array.isArray(inputs[file])) errors.push(`${file} is missing or is not an array`);
  for (const { file } of OBJECT_INPUTS) if (!isObject(inputs[file])) errors.push(`${file} is missing or is not an object`);
  if (errors.length) return { ok: false, errors };

  const validator = createValidator(schemas);
  const schemaErrors = (schemaFile, value, name) => {
    const result = validator.validate(schemaFile, value);
    return result.ok ? [] : result.errors.map((x) => `${name}: fails ${schemaFile} at ${x.path || '/'} [${x.keyword}] ${x.message}`);
  };

  // ---------------------------------------------------------------- every entity, with its schema
  const entities = [];
  for (const { file, schema } of ARRAY_INPUTS) {
    inputs[file].forEach((value, i) => entities.push({ file, schema, value, name: nameOf(value, `${file}[${i}]`) }));
  }
  for (const { file, schema } of OBJECT_INPUTS) entities.push({ file, schema, value: inputs[file], name: nameOf(inputs[file], file) });

  const seen = new Map();
  for (const entity of entities) {
    if (!isObject(entity.value) || typeof entity.value.id !== 'string') {
      errors.push(`${entity.name}: has no identifier, so it cannot be matched to a verdict`);
      continue;
    }
    if (seen.has(entity.name)) errors.push(`${entity.name}: the identifier occurs twice (${seen.get(entity.name)} and ${entity.file})`);
    else seen.set(entity.name, entity.file);
  }

  // Nothing fails the contracts.
  for (const entity of entities) errors.push(...schemaErrors(entity.schema, entity.value, entity.name));

  // Nothing unverified ships: a pass verdict whose hash equals the entity's canonical-JSON hash.
  for (const entity of entities) {
    if (!isObject(entity.value) || typeof entity.value.id !== 'string') continue;
    const records = verification.entities.filter((r) => isObject(r) && r.id === entity.name);
    if (records.length === 0) {
      errors.push(`${entity.name}: no verdict in the verification record`);
      continue;
    }
    const refused = records.filter((r) => r.verdict !== 'pass');
    if (refused.length) {
      errors.push(`${entity.name}: verdict ${refused.map((r) => JSON.stringify(r.verdict)).join(', ')} in the verification record`);
      continue;
    }
    const hash = await entityHash(entity.value);
    if (!records.some((r) => r.hash === hash)) {
      errors.push(`${entity.name}: its canonical-JSON SHA-256 ${hash} differs from the verified hash (edited after verification?)`);
    }
  }

  // ---------------------------------------------------------------- regrouping by trend
  const trends = inputs['trends.json'];
  const trendIds = new Set(trends.filter(isObject).map((t) => t.id));
  const readings = inputs['readings.json'];
  const interrogations = inputs['interrogations.json'];
  const conversations = inputs['conversations.json'];

  for (const r of readings) if (!isObject(r) || !trendIds.has(r.trendId)) errors.push(`${nameOf(r, 'a reading')}: its trendId names no trend`);
  for (const q of interrogations) if (!isObject(q) || !trendIds.has(q.trendId)) errors.push(`${nameOf(q, 'an interrogation')}: its trendId names no trend`);
  for (const c of conversations) if (!isObject(c) || !trendIds.has(c.trendId)) errors.push(`${nameOf(c, 'a conversation set')}: its trendId names no trend`);

  const bundles = new Map();
  const conversationByTrend = new Map();
  for (const trend of trends) {
    if (!isObject(trend) || typeof trend.id !== 'string') continue;
    const own = readings.filter((r) => isObject(r) && r.trendId === trend.id);
    const questioning = interrogations.filter((q) => isObject(q) && q.trendId === trend.id);
    if (questioning.length !== 1) errors.push(`${trend.id}: expected one interrogation, found ${questioning.length}`);
    const refs = Array.isArray(trend.readings) ? trend.readings : [];
    for (const r of own) {
      const ref = refs.find((x) => isObject(x) && x.lens === r.lens);
      if (!ref || ref.readingId !== r.id) errors.push(`${r.id}: not the reading ${trend.id} holds for lens ${JSON.stringify(r.lens)}`);
    }
    const bundle = { trendId: trend.id, readings: own, interrogation: questioning[0] };
    errors.push(...schemaErrors('reveal-bundle.schema.json', bundle, `reveal bundle of ${trend.id}`));
    bundles.set(trend.id, bundle);

    if (conversations.length > 0) {
      // Either every trend has one conversation module or none does (M1-U9).
      const sets = conversations.filter((c) => isObject(c) && c.trendId === trend.id);
      if (sets.length !== 1) errors.push(`${trend.id}: expected one conversation set, found ${sets.length} (a partial set would make the manifest untrue)`);
      else conversationByTrend.set(trend.id, sets[0]);
    }
  }

  if (errors.length) return { ok: false, errors };

  // ---------------------------------------------------------------- the files
  const values = new Map([
    ['data/signals.js', inputs['signals.json']],
    ['data/trends.js', trends],
    ['data/log.js', inputs['log.json']],
    ['data/brief.js', inputs['brief.json']],
    ['data/readiness.js', inputs['readiness.json']],
    ['data/governance.js', inputs['governance.json']],
  ]);
  for (const [trendId, bundle] of bundles) values.set(`data/reveal/${trendId}.js`, bundle);
  for (const [trendId, set] of conversationByTrend) values.set(`data/conversation/${trendId}.js`, set);

  const modules = [...values.keys(), 'data/freeze.js'].sort(byCodePoint);
  const manifest = { frozenOn, pipelineRunOn, modules };
  errors.push(...schemaErrors('freeze-manifest.schema.json', manifest, 'data/freeze.js'));
  if (errors.length) return { ok: false, errors };
  values.set('data/freeze.js', manifest);

  const files = new Map();
  for (const path of modules) files.set(path, moduleText(values.get(path), frozenOn));
  return { ok: true, files };
}
