// M1 Data contracts, the freeze step: unit tests M1-U11, M1-U13, M1-U14 and M1-U16.
// Written from docs/04-module-design.md (M1) and docs/03-architecture.md (section 4) before
// pipeline/freeze-core.mjs or pipeline/freeze.mjs exists (test-first rule).
//
// The interface is fixed in docs/03-architecture.md, section 4:
//   freeze({ inputs, verification, schemas, frozenOn, pipelineRunOn })
//     -> { ok: true, files: Map<repository path, file text> } | { ok: false, errors }; never throws
//   inputs        keyed by pipeline/output/ file name, each value the parsed JSON.
//   verification  { entities: [{ type, id, hash, verdict, note }] }, matched by id; hash is the
//                 SHA-256 hex of the entity's canonical JSON.
//   output        arrays keep their input order; the manifest's modules are sorted by code point
//                 and include data/freeze.js; conversation modules only if conversations.json has
//                 entries.
//   driver        `node pipeline/freeze.mjs [--frozen-on YYYY-MM-DD] [--pipeline-run-on YYYY-MM-DD]`,
//                 run from the repository root, reads pipeline/output/ and writes data/.

import { test } from '../lib/harness.mjs';
import { assert } from '../lib/assert.mjs';
import {
  importUnderTest, importJson, readText, listFiles, nodeBuiltin, repoUrl,
} from '../lib/env.mjs';
import { SCHEMAS } from '../lib/schemas.mjs';
import { loadContent, clone } from '../lib/content.mjs';
import { entityHash } from '../lib/canonical.mjs';

const CORE = repoUrl('pipeline/freeze-core.mjs');
const PIPELINE_FILES = Object.freeze([
  'signals.json', 'trends.json', 'readings.json', 'interrogations.json', 'conversations.json',
  'brief.json', 'readiness.json', 'governance.json', 'log.json',
]);
const FROZEN_ON = '2026-10-05';
const PIPELINE_RUN_ON = '2026-10-04';
const HEADER = /^\/\/ Frozen at G3 on \d{4}-\d{2}-\d{2} from pipeline\/output\/\. Generated by pipeline\/freeze-core\.mjs; do not edit by hand\.$/;

async function pipelineFixture(dir = 'tests/fixtures/pipeline/') {
  const inputs = {};
  for (const file of PIPELINE_FILES) inputs[file] = clone(await importJson(repoUrl(dir + file)));
  const verification = clone(await importJson(repoUrl(`${dir}verification.json`)));
  return { inputs, verification };
}

async function runCore(core, { inputs, verification }, dates = {}) {
  return core.freeze({
    inputs,
    verification,
    schemas: SCHEMAS,
    frozenOn: dates.frozenOn || FROZEN_ON,
    pipelineRunOn: dates.pipelineRunOn || PIPELINE_RUN_ON,
  });
}

/** The value a frozen module exports, parsed from its text. */
function parseModule(text) {
  const body = text.slice(text.indexOf('\n') + 1);
  const m = /^export default ([\s\S]*);\n$/.exec(body);
  if (!m) throw new Error('not of the form "export default <literal>;\\n"');
  return JSON.parse(m[1]);
}

function noFiles(result) {
  return result.files === undefined || result.files === null || (result.files instanceof Map && result.files.size === 0);
}

// ------------------------------------------------------------------------------------------ M1-U11

test('M1-U11 the freeze core refuses unverified, edited or invalid entities and produces no files', async () => {
  const core = await importUnderTest(CORE);
  const problems = [];

  // Control: the untouched fixture freezes, so the refusals below are caused by the mutations.
  const control = await runCore(core, await pipelineFixture());
  if (!control || control.ok !== true || !(control.files instanceof Map) || control.files.size === 0) {
    problems.push(`the unmodified fixture did not freeze: ${JSON.stringify(control && control.errors)}`);
  }

  const cases = [];
  {
    const f = await pipelineFixture();
    const id = 'sig-2026-03-04-zebra-gamma';
    f.verification.entities.find((e) => e.id === id).verdict = 'struck';
    cases.push({ label: 'a struck verdict', id, f });
  }
  {
    const f = await pipelineFixture();
    const id = 'conversation-fixture-beta';
    f.verification.entities = f.verification.entities.filter((e) => e.id !== id);
    cases.push({ label: 'no verdict at all', id, f });
  }
  {
    const f = await pipelineFixture();
    const id = 'trend-fixture-alpha';
    f.inputs['trends.json'].find((t) => t.id === id).summary += ' Edited after verification.';
    cases.push({ label: 'text edited after verification (hash differs)', id, f });
  }
  {
    const f = await pipelineFixture();
    const id = 'reading-fixture-alpha-threat';
    const reading = f.inputs['readings.json'].find((r) => r.id === id);
    reading.score = 'x';
    f.verification.entities.find((e) => e.id === id).hash = await entityHash(reading);
    cases.push({ label: 'a schema violation with a matching hash', id, f });
  }

  for (const c of cases) {
    let result;
    try {
      result = await runCore(core, c.f);
    } catch (error) {
      problems.push(`${c.label}: the core threw instead of returning { ok: false }: ${error && error.message}`);
      continue;
    }
    if (!result || result.ok !== false) problems.push(`${c.label}: the core did not return { ok: false }`);
    else {
      if (!noFiles(result)) problems.push(`${c.label}: files were produced`);
      if (!JSON.stringify(result.errors || []).includes(c.id)) problems.push(`${c.label}: no error names ${c.id}`);
    }
  }
  assert.none(problems, 'freeze-core refusals that did not happen');
});

test('M1-U11 the Node freeze driver, given the date flags, exits non-zero and leaves data/ byte-identical when the core refuses', { needs: ['fs'], timeout: 60000 }, async () => {
  const fs = await nodeBuiltin('node:fs/promises');
  const os = await nodeBuiltin('node:os');
  const path = await nodeBuiltin('node:path');
  const url = await nodeBuiltin('node:url');
  const cp = await nodeBuiltin('node:child_process');
  const repo = url.fileURLToPath(repoUrl(''));
  for (const required of ['pipeline/freeze.mjs', 'pipeline/freeze-core.mjs']) {
    await fs.access(path.join(repo, required)).catch(() => {
      throw new Error(`module under test is missing: ${required} (expected before implementation, test-first rule)`);
    });
  }
  const flags = ['--frozen-on', FROZEN_ON, '--pipeline-run-on', PIPELINE_RUN_ON];
  const temps = [];

  // A minimal copy of the repository: the drivers, the interpreter, the schemas and the fixture
  // pipeline output, optionally with one verdict struck; data/ holds a sentinel file.
  async function copy(struck) {
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'periscope-freeze-'));
    temps.push(tmp);
    for (const rel of ['pipeline/freeze.mjs', 'pipeline/freeze-core.mjs', 'tests/lib/mini-schema.mjs']) {
      await fs.mkdir(path.dirname(path.join(tmp, rel)), { recursive: true });
      await fs.copyFile(path.join(repo, rel), path.join(tmp, rel));
    }
    await fs.cp(path.join(repo, 'schemas'), path.join(tmp, 'schemas'), { recursive: true });
    await fs.cp(path.join(repo, 'tests/fixtures/pipeline'), path.join(tmp, 'pipeline/output'), { recursive: true });
    if (struck) {
      const verificationPath = path.join(tmp, 'pipeline/output/verification.json');
      const verification = JSON.parse(await fs.readFile(verificationPath, 'utf8'));
      verification.entities.find((e) => e.id === struck).verdict = 'struck';
      await fs.writeFile(verificationPath, `${JSON.stringify(verification, null, 2)}\n`);
    }
    await fs.mkdir(path.join(tmp, 'data'), { recursive: true });
    await fs.writeFile(path.join(tmp, 'data/sentinel.js'), '// sentinel: must survive a refused freeze\n');
    return tmp;
  }
  const run = (tmp) => cp.spawnSync(process.execPath, [path.join(tmp, 'pipeline/freeze.mjs'), ...flags], { cwd: tmp, encoding: 'utf8', timeout: 25000 });
  const snapshot = async (tmp) => {
    const out = {};
    for (const f of await listFiles(url.pathToFileURL(path.join(tmp, 'data') + path.sep))) {
      out[f] = await fs.readFile(path.join(tmp, 'data', f), 'utf8');
    }
    return out;
  };

  try {
    // Control: with the flags and nothing struck, the driver succeeds and honours the dates, so the
    // refusal below is caused by the struck verdict, not by the flags.
    const ok = await copy(null);
    const control = run(ok);
    assert.equal(control.status, 0, `driver exit status on the unmodified fixture (${control.stderr})`);
    assert.equal(
      await fs.readFile(path.join(ok, 'data/freeze.js'), 'utf8'),
      await readText(repoUrl('tests/fixtures/expected-data/freeze.js')),
      'data/freeze.js written with the flagged dates',
    );

    const struck = 'sig-2026-03-04-zebra-gamma';
    const tmp = await copy(struck);
    const before = await snapshot(tmp);
    const refused = run(tmp);
    const after = await snapshot(tmp);
    assert.notEqual(refused.status, 0, 'driver exit status');
    assert.ok(`${refused.stdout}${refused.stderr}`.includes(struck), `the driver reports the refused entity ${struck}`);
    assert.deepEqual(after, before, 'data/ after the refused freeze');
  } finally {
    for (const tmp of temps) await fs.rm(tmp, { recursive: true, force: true });
  }
});

// ------------------------------------------------------------------------------------------ M1-U13

test('M1-U13 the freeze core is deterministic and its output equals the expected values', async () => {
  const core = await importUnderTest(CORE);
  const first = await runCore(core, await pipelineFixture());
  const second = await runCore(core, await pipelineFixture());
  assert.ok(first && first.ok === true && first.files instanceof Map, 'the fixture freezes');
  assert.deepEqual([...first.files.keys()].sort(), [...second.files.keys()].sort(), 'file set on a second run');
  for (const [p, text] of first.files) assert.equal(second.files.get(p), text, `second run, ${p}`);

  const manifest = (await import(repoUrl('tests/fixtures/expected-data/freeze.js').href)).default;
  assert.deepEqual([...first.files.keys()].sort(), [...manifest.modules].sort(), 'files produced against the expected manifest');
  for (const p of manifest.modules) {
    const expected = (await import(repoUrl(`tests/fixtures/expected-data/${p.slice('data/'.length)}`).href)).default;
    assert.deepEqual(parseModule(first.files.get(p)), expected, p);
  }
});

test('M1-U13 the freeze core output equals tests/fixtures/expected-data byte for byte', async () => {
  const core = await importUnderTest(CORE);
  const result = await runCore(core, await pipelineFixture());
  assert.ok(result && result.ok === true && result.files instanceof Map, 'the fixture freezes');
  const expectedFiles = (await listFiles(repoUrl('tests/fixtures/expected-data/'))).map((f) => `data/${f}`);
  assert.deepEqual([...result.files.keys()].sort(), expectedFiles, 'file set');
  for (const p of expectedFiles) {
    const expected = await readText(repoUrl(`tests/fixtures/expected-data/${p.slice('data/'.length)}`));
    assert.equal(result.files.get(p), expected, p);
  }
});

test('M1-U13 the freeze core on pipeline/output reproduces the committed data/ byte for byte', { needs: ['data'] }, async () => {
  const core = await importUnderTest(CORE);
  const manifest = (await importUnderTest(repoUrl('data/freeze.js'))).default;
  const result = await runCore(core, await pipelineFixture('pipeline/output/'), manifest);
  assert.ok(result && result.ok === true && result.files instanceof Map, `pipeline/output freezes: ${JSON.stringify(result && result.errors)}`);
  const committed = (await listFiles(repoUrl('data/'))).filter((f) => !f.startsWith('.') && !f.includes('/.'));
  assert.deepEqual([...result.files.keys()].sort(), committed.map((f) => `data/${f}`), 'file set');
  for (const f of committed) assert.equal(result.files.get(`data/${f}`), await readText(repoUrl(`data/${f}`)), `data/${f}`);
});

// ------------------------------------------------------------------------------------------ M1-U14

/**
 * The problems that make a module text not inert. Words are looked for outside JSON string
 * literals only, so that prose such as "an important new standard" in a summary is not mistaken
 * for code; inside a string literal nothing can execute.
 */
function inertProblems(text, file) {
  const problems = [];
  const newline = text.indexOf('\n');
  const header = newline >= 0 ? text.slice(0, newline) : text;
  if (!HEADER.test(header)) problems.push(`${file}: first line is not the fixed freeze header`);
  const body = newline >= 0 ? text.slice(newline + 1) : '';
  const m = /^export default ([\s\S]*);\n$/.exec(body);
  if (!m) {
    problems.push(`${file}: body is not "export default <literal>;" followed by one newline`);
    return problems;
  }
  const outsideStrings = body.replace(/"(?:[^"\\\n]|\\.)*"/g, '""');
  const exportsCount = (outsideStrings.match(/\bexport\b/g) || []).length;
  if (exportsCount !== 1) problems.push(`${file}: ${exportsCount} export statements`);
  for (const [what, re] of [['import', /\bimport\b/], ['function', /\bfunction\b/], ['=>', /=>/], ['new ', /\bnew /], ['backtick', /`/]]) {
    if (re.test(outsideStrings)) problems.push(`${file}: contains ${what}`);
  }
  try {
    JSON.parse(m[1]);
  } catch (error) {
    problems.push(`${file}: the exported value is not a plain literal (${error.message})`);
  }
  return problems;
}

test('M1-U14 every expected-data module is inert', async () => {
  const manifest = (await import(repoUrl('tests/fixtures/expected-data/freeze.js').href)).default;
  // Guard: the check must recognise code, or it could not fail.
  const bad = `// Frozen at G3 on 2026-10-05 from pipeline/output/. Generated by pipeline/freeze-core.mjs; do not edit by hand.\nexport default (() => 1)();\n`;
  assert.ok(inertProblems(bad, 'guard').length > 0, 'an arrow function is detected');
  const problems = [];
  for (const p of manifest.modules) {
    const file = `tests/fixtures/expected-data/${p.slice('data/'.length)}`;
    problems.push(...inertProblems(await readText(repoUrl(file)), file));
  }
  assert.none(problems, 'non-inert modules');
});

test('M1-U14 the expected-data manifest lists exactly the files present', { needs: ['fs'] }, async () => {
  const manifest = (await import(repoUrl('tests/fixtures/expected-data/freeze.js').href)).default;
  const present = (await listFiles(repoUrl('tests/fixtures/expected-data/'))).map((f) => `data/${f}`);
  assert.deepEqual([...manifest.modules].sort(), present);
});

test('M1-U14 every module in data/ is inert', { needs: ['data'] }, async () => {
  const manifest = (await importUnderTest(repoUrl('data/freeze.js'))).default;
  const problems = [];
  for (const p of manifest.modules) problems.push(...inertProblems(await readText(repoUrl(p)), p));
  assert.none(problems, 'non-inert modules in data/');
});

test('M1-U14 the data/ manifest lists exactly the files in data/', { needs: ['data', 'fs'] }, async () => {
  const manifest = (await importUnderTest(repoUrl('data/freeze.js'))).default;
  // Dotfiles (data/.gitkeep) are not modules and are not served as content; they are ignored here.
  const present = (await listFiles(repoUrl('data/'))).filter((f) => !f.split('/').some((s) => s.startsWith('.')));
  assert.deepEqual([...manifest.modules].sort(), present.map((f) => `data/${f}`));
});

// ------------------------------------------------------------------------------------------ M1-U16

test('M1-U16 every entity in data/ has a pass verdict whose hash matches its canonical JSON', { needs: ['data'] }, async () => {
  const verification = await importJson(repoUrl('pipeline/output/verification.json'));
  const content = await loadContent({ from: 'data' });
  const entities = [
    ...content.signals,
    ...content.trends,
    ...Object.values(content.reveal).flatMap((b) => [...b.readings, b.interrogation]),
    ...Object.values(content.conversation),
    ...content.log,
    content.readiness,
    content.governance,
    content.brief,
  ];
  const problems = [];
  for (const entity of entities) {
    const hash = await entityHash(entity);
    const verdicts = (verification.entities || []).filter((v) => v.id === entity.id);
    if (!verdicts.some((v) => v.verdict === 'pass' && v.hash === hash)) {
      problems.push(`${entity.id}: no pass verdict with hash ${hash} (found ${JSON.stringify(verdicts.map((v) => [v.verdict, v.hash]))})`);
    }
  }
  assert.none(problems, 'entities without a matching pass verdict');
});
